# fly.toml app configuration file generated for hodari-gardens on 2026-02-23T09:09:31+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hodari-gardens'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048

[[http_service.checks]]
grace_period = "30s"
interval = "15s"
method = "GET"
path = "/health"
protocol = "http"
timeout = "5s"
tls_skip_verify = false
